### PR TITLE
Dummy deployment

### PR DESCRIPTION
**Pull request by SarthakSingh18**
In this PR I have created dummy deployment files which includes
1. master-nodeport.yaml which directs request to master pod to port 80 where Nginx is listening.
2. master.yaml which includes configuration of two containers one is Nginx and another is alpine(which will be used to get IP of slave nodes using headless service).
3. slave-headless.yaml which will help to get pod IP.
4. slave.yaml which is running alpine image. 

I have not used the busy box container due to some errors and it is not able to get the IP address of slave containers.
I am now implementing HPA on slave nodes.
I have used Nginx because I have to check if nodeport is working or not.

Illustration:
Annotation 2021-07-09 201944

@1209973  @ravindudsilva @kmehant Please review this PR and let me know the changes

### CODE REVIEW

**Comment by SarthakSingh18** [comment]
kubectl get all

**Comment by kmehant** [comment]
@SarthakSingh18 Can you visualize your K8s deployment. Come up with an abstract diagram showing the containers, pods, and node port that you have created and attach it here.

**Review by kmehant — CHANGES_REQUESTED** [review]
Please come up with an abstract diagram mentioning this whole setup using arrows to show communication flow.

**Comment by SarthakSingh18** [comment]
Okay, @kmehant I will attach the abstract diagram.

**Comment by SarthakSingh18** [comment]
As this is dummy deployment So I have created Nodeport Service which handles requests and directs those requests to the Coordinator pod for confirmation if this Nodeport service is working or not I have created 2 containers in the Coordinator pod

1. The first container is listening at port 80 and serves the Nginx default page which shows the Nodeport service is working.
2. The second container(alpine) is used to getting the IP addresses of all the slave nodes using headless service. 
3. Currently I am working on HPA on slave nodes and figuring out a way to test it.

Annotation 2021-07-09 201944

**Comment by kmehant** [comment]
> > @SarthakSingh18 Can you visualize your K8s deployment. Come up with an abstract diagram showing the containers, pods, replicaset and node port that you have created and attach it here.
> 
> As this is dummy deployment So I have created Nodeport Service which handles requests and directs those requests to the Coordinator pod for confirmation if this Nodeport service is working or not I have created 2 containers in the Coordinator pod
> 
> 1. The first container is listening at port 80 and serves the Nginx default page which shows the Nodeport service is working.
> 2. The second container(alpine) is used to getting the IP addresses of all the slave nodes using headless service.
> 3. Currently I am working on HPA on slave nodes and figuring out a way to test it.
> 
> Annotation 2021-07-09 201944
> 
> @kmehant @ravindudsilva

Looks good @SarthakSingh18 

Can you put a screenshot of the logs at alpine container showing the IPs of slave pods that are retrieved through headless service?

**Comment by SarthakSingh18** [comment]
> > > @SarthakSingh18 Can you visualize your K8s deployment. Come up with an abstract diagram showing the containers, pods, replicaset and node port that you have created and attach it here.
> > 
> > 
> > As this is dummy deployment So I have created Nodeport Service which handles requests and directs those requests to the Coordinator pod for confirmation if this Nodeport service is working or not I have created 2 containers in the Coordinator pod
> > 
> > 1. The first container is listening at port 80 and serves the Nginx default page which shows the Nodeport service is working.
> > 2. The second container(alpine) is used to getting the IP addresses of all the slave nodes using headless service.
> > 3. Currently I am working on HPA on slave nodes and figuring out a way to test it.
> > 
> > Annotation 2021-07-09 201944
> > @kmehant @ravindudsilva
> 
> Looks good @SarthakSingh18
> 
> Can you put a screenshot of the logs at alpine container showing the IPs of slave pods that are retrieved through headless service?

Annotation 2021-07-09 212141

**Comment by SarthakSingh18** [comment]
Annotation 2021-07-09 212141
@kmehant

**Comment by kmehant** [comment]
> Annotation 2021-07-09 212141
> @kmehant

Aren't we getting this information from a program? What is the purpose of the alpine container?

**Comment by SarthakSingh18** [comment]
> > Annotation 2021-07-09 212141
> > @kmehant
> 
> Aren't we getting this information from a program? What is the purpose of the alpine container?

Can you please tell me what program are you talking about?

**Comment by kmehant** [comment]
> The alpine container is only used to test the headless service which I have created.
@SarthakSingh18 
Can't we test this directly from the Nginx container that you used here? Your bootstrap can be much simpler right in this way (single container in master pod)?

**Comment by kmehant** [comment]
Also @SarthakSingh18 I guess Alpine Linux containers use busybox under the hood to enable Unix tools. Why are you targeting busybox base image directly itself? any specific reasons?

**Comment by SarthakSingh18** [comment]
> > The alpine container is only used to test the headless service which I have created.
> 
> @SarthakSingh18
> 
> Can't we test this directly from the Nginx container that you used here? Your bootstrap can be much simpler right in this way (single container in co-ordinator pod)?

Yes, bootstrap will be simpler in this way but nslookup and other tools are not available in the Nginx container and I won't be able to download that tools in the Nginx container so that's why I have used another container.

**Comment by SarthakSingh18** [comment]
> Also @SarthakSingh18 I guess Alpine Linux containers use busybox under the hood to enable Unix tools. Why are you targeting busybox base image directly itself? any specific reasons?

@kmehant In the coordinator pod instead of alpine I have tried busy box container but it cannot look for the services so I tried searching it on google and didn't find anything so when I tried alpine container instead of the busy box container alpine container is able to lookup for the services.

**Review by kmehant — APPROVED** [review]

**Pull request merged**
